add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[](bold green)"     # The "success_symbol" is being set to "➜" with the color "bold green"
success_symbol = "[](bold green)"     # The "success_symbol" is being set to "➜" with the color "bold green"
# success_symbol = "[➜](bold green)"     # The "success_symbol" is being set to "➜" with the color "bold green"

# format = """
# $username\
# $hostname\
# $shlvl\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $hg_branch\
# $docker_context\
# $package\
# $cmake\
# $dart\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $helm\
# $java\
# $julia\
# $nim\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $purescript\
# $python\
# $ruby\
# $rust\
# $swift\
# $terraform\
# $zig\
# $nix_shell\
# $conda\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $env_var\
# $crystal\
# $custom\
# $cmd_duration\
# $line_break\
# $lua\
# $jobs\
# $battery\
# $time\
# $status\
# $kubernetes\
# $character"""

[gcloud]
disabled = true

[aws]
symbol = " "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[cmd_duration]
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
truncation_length = 8
truncation_symbol = "…/"

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[kubernetes]
format = '[k8s@$namespace](green) '
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = " NodeJS"

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "
disabled = true

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[status]
disabled = true

[swift]
symbol = "ﯣ "

[time]
disabled = true
use_12hr = true
style = "dimmed white"
