

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$kubernetes\
$cmd_duration $jobs $time\
$line_break\
$battery\
$character"""

[fill]
symbol = " "

[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[](bold bright-purple)"     # The "success_symbol" is being set to "➜" with the color "bold green"
# success_symbol = "[](bold bright-purple)"     # The "success_symbol" is being set to "➜" with the color "bold green"
# success_symbol = "[](bold purple)"     # The "success_symbol" is being set to "➜" with the color "bold green"
# success_symbol = "[聾](bold bright-purple)"     # The "success_symbol" is being set to "➜" with the color "bold green"
success_symbol = "[](bold #ebbcba)"     # The "success_symbol" is being set to "➜" with the color "bold green"

[aws]
symbol = " "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[cmd_duration]
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
style = "bold #6e6a86"
truncation_length = 8
truncation_symbol = "…/"

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[kubernetes]
format = '[k8s@$namespace](green) '
disabled = true

[git_branch]
# symbol = " "
symbol = "  "
style = "bright-purple"
format = ' [$symbol$branch(:$remote_branch)]($style) '

[git_metrics]
added_style = 'bold blue'
disabled = false
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
style = "#eb6f92"
disabled = true

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = " NodeJS"

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "
disabled = true

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[status]
disabled = true

[swift]
symbol = "ﯣ "

[time]
disabled = true
use_12hr = true
style = "dimmed white"
