# NOTE SETTINGS
[note]
language = "en"
default-title = "Untitled"
filename = "{{slug title}}-{{date now}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

# EXTRA VARIABLES
[extra]
author = "rs"

# GROUP OVERRIDES
[group.ts]
[group.ts.note]
filename = "{{title}}_{{date now}}"
template = "ts.md"

[group.any]
[group.any.note]
filename = "{{title}}_{{date now}}"
template = "any.md"

[group.private]
[group.private.note]
filename = "{{title}}_{{date now}}"
template = "private.md"



# MARKDOWN SETTINGS
[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"
# Pager used to scroll through long output.
pager = "less -FIRX"
# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]
# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"
# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

ts = 'zk new "$ZK_NOTEBOOK_DIR/ts" --group ts --title "$*"'
any = 'zk new "$ZK_NOTEBOOK_DIR/any" --group any --title "$*"'
private = 'zk new "$ZK_NOTEBOOK_DIR/private" --group private --title "$*"'

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
