-- local Popup = require 'nui.popup'
-- local event = require('nui.utils.autocmd').event
--
-- local popup = Popup {
--   enter = true,
--   focusable = true,
--   border = {
--     style = 'rounded',
--   },
--   position = '50%',
--   size = {
--     width = '80%',
--     height = '60%',
--   },
--   buf_options = {
--     modifiable = true,
--     readonly = false,
--   },
-- }
--
-- -- mount/open the component
-- popup.on(event.BufEnter, function()
--   popup:mount()
--   -- Get current buffer name
--   -- vim.api.nvim_buf_get_name(0)
-- end)
--
-- -- unmount component when cursor leaves buffer
-- popup:on(event.BufLeave, function()
--   popup:unmount()
-- end)
--
-- -- set content
--
-- vim.api.nvim_buf_set_lines(popup.bufnr, 0, 1, false, { 'Hello World' })

-- local Popup = require 'nui.popup'
-- local event = require('nui.utils.autocmd').event
--
-- local popup = Popup {
--   enter = false,
--   focusable = false,
--   border = {
--     style = 'rounded',
--   },
--   position = {
--     row = 1,
--     col = '50%',
--   },
--   size = {
--     width = '80%',
--     height = '6%',
--   },
--   buf_options = {
--     modifiable = true,
--     readonly = false,
--   },
-- }
--
-- -- mount/open the component
-- popup:mount()
--
-- -- unmount component when cursor leaves buffer
-- popup:on(event.BufLeave, function()
--   popup:unmount()
-- end)
--
-- -- set content
